//
// Created by aaama on 17/01/2023.
//

#ifndef B_CPP_500_REN_5_2_RTYPE_AUDREY_AMAR_ACCELERATIONCOMPONENT_H
#define B_CPP_500_REN_5_2_RTYPE_AUDREY_AMAR_ACCELERATIONCOMPONENT_H


class AccelerationComponent {
    size_t x;
    size_t y;
};


#endif //B_CPP_500_REN_5_2_RTYPE_AUDREY_AMAR_ACCELERATIONCOMPONENT_H
