//
// Created by aaama on 17/01/2023.
//

#ifndef B_CPP_500_REN_5_2_RTYPE_AUDREY_AMAR_TEAMCOMPONENT_H
#define B_CPP_500_REN_5_2_RTYPE_AUDREY_AMAR_TEAMCOMPONENT_H


class TeamComponent {
    Team team;
};


#endif //B_CPP_500_REN_5_2_RTYPE_AUDREY_AMAR_TEAMCOMPONENT_H
