name: Compilation check

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run build script
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: ./build.bat