name: Compilation check

on: [push]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run build script windows
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: ./build.bat

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install CMake and ninja
        run:  |
          sudo apt-get update
          sudo apt-get install -y ninja-build
          wget -q https://github.com/Kitware/CMake/releases/download/v3.24.0/cmake-3.24.0-linux-x86_64.tar.gz
          tar xf cmake-3.24.0-linux-x86_64.tar.gz
          export PATH=$PWD/cmake-3.24.0-linux-x86_64/bin:$PATH
      - name: Run build script linux
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: ./build.sh